version: '2'

services:
 zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - 2181:2181
 kafka:
  image: wurstmeister/kafka
  links:
    - zookeeper:zk
  ports:
    - 9092:9092
  depends_on:
    - zookeeper
  environment:
     KAFKA_ADVERTISED_HOST_NAME: 172.17.118.107
     KAFKA_ADVERTISED_PORT: 9092
     KAFKA_ZOOKEEPER_CONNECT: zk:2181
 redis:
  image: redis
  ports:
   - 6379:6379
 mysql:
  image: mysql:5.5.60
  ports:
   - 172.17.118.107:3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
   